### ISSUE TITLE
SkillTable - First names players

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1026]
Original [issue 1026](https://code.google.com/p/foxtrick/issues/detail?id=1026) created by [josoetgebrook](mailto:josoetgebrook@gmail.com) on 2012-12-20T14:15:31.000Z:

Since version 0.11.0 the Players first names are shortened to the first letter in the SkillTable.

Is it possible to let us choose which what we want: 1 letter of the whole first name.

I use data from the SkillTable to export it to an Excel-sheet.

Greets
Jos

**Comment by EmreBkts** [comment]
ık
