### ISSUE TITLE
Convert "My Hattrick calendar" from HT to local time

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1043]
Original [issue 1043](https://code.google.com/p/foxtrick/issues/detail?id=1043) created by [CatzHoek](mailto:CatzHoek@gmail.com) on 2013-02-25T00:43:20.000Z:

**From:** crabGoblin
**PostID:** [(14932093.994)](https://www.hattrick.org/goto.ashx?path=/Forum/Read.aspx%3Ft%3D14932093%26n%3D994%26v%3D4)
**Reply:** [(14932093.1)](https://www.hattrick.org/goto.ashx?path=/Forum/Read.aspx%3Ft%3D14932093%26n%3D1%26v%3D4)
**To:** LA-MJ
**Datetime:** 12.02.2013 2at 3:03
**Message:** 
Would Foxtrick be able to re-arrange the events in the My Hattrick calendar, so that they appear in local time? For example, I have an upcoming Cup match at 01:00 Thursday HT time, but locally (EST) that is 7:00 PM on Wednesday. It would be nice if I didn't have to translate the time zones every thime, but even if it just put it on the Wednesday tab it would be helpful.

**Comment by SparKot** [comment]
Are there any provisons in GitHub to vote-up feature-requests?

**Comment by minj** [comment]
No, but you can use https://www.zenhub.io/

**Comment by minj** [comment]
HTs are doing some stuff in timezones area

**Comment by minj** [comment]
Alright this will be done by HTs
