### ISSUE TITLE
Add player notes as an icon tooltip on the team players page

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1229]
Original [issue 1229](https://code.google.com/p/foxtrick/issues/detail?id=1229) created by [kosio.petkov](mailto:kosio.petkov@gmail.com) on 2014-08-15T19:13:23.000Z:

Hello,

I often use the Notes for players, especially those in the academy. When I open the players list I have to open each player's page to see the notes I've added. Instead, it would be useful to have a &quot;Notes&quot; link for every player with notes so that I can see them on hover (tooltip like).

Thanks!

**Comment by minj** [comment]
it seems CHPP is buggy concerning this

**Comment by ventouris** [comment]
This will be possible since I added owner notes on the CHPP for players xml

**Comment by minj** [comment]
![match-icons](https://user-images.githubusercontent.com/1035523/68144078-29ba4900-ff33-11e9-9fd6-635af9ae15bb.png)
