### ISSUE TITLE
Frozen columns in skill table

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1232]
Original [issue 1232](https://code.google.com/p/foxtrick/issues/detail?id=1232) created by [minj](mailto:4mr.minj@gmail.com) on 2014-09-28T23:02:00.000Z:

**From:** LA-MJ
**PostID:** [(16412248.256)](https://www.hattrick.org/goto.ashx?path=/Forum/Read.aspx%3Ft%3D16412248%26n%3D256%26v%3D4)
**Reply:** [(16412248.254)](https://www.hattrick.org/goto.ashx?path=/Forum/Read.aspx%3Ft%3D16412248%26n%3D254%26v%3D4)
**To:** -Yaute-
**Datetime:** 2014-08-19 1at 2:21
**Message:** 
[q]
-Yaute- rašė:

Hello,

I don't know if it's possible to have a &quot;static&quot; column in the skill players table
Because when we have several columns and when we scroll it will be great to see the name of the players.
Something like this:
(http://i.imgur.com/DWmXyM3.png) ![http://i.imgur.com/DWmXyM3.png](http://i.imgur.com/DWmXyM3.png)

What do you think?
[/q]

freezed columns are not supported natively in the web but one can always try to hack a custom solution

I can't promiss anything though, since we have already run into browser limitations previously (for an unrelated layout problem)

**From:** LA-MJ
**PostID:** [(16412248.258)](https://www.hattrick.org/goto.ashx?path=/Forum/Read.aspx%3Ft%3D16412248%26n%3D258%26v%3D4)
**Reply:** [(16412248.257)](https://www.hattrick.org/goto.ashx?path=/Forum/Read.aspx%3Ft%3D16412248%26n%3D257%26v%3D4)
**To:** Dantekavala
**Datetime:** 2014-08-19 1at 2:33
**Message:** 
yes, I looked at the first few google results and all of them scream 'TMI' to me.

in the end it will be a simple double-table hack like this:(https://stackoverflow.com/questions/20759920/...ut-js) https://stackoverflow.com/questions/20759920/html-table-with-fixed-header-column-and-row-without-js

the problem is we already use overflow CSS there and float does not always play nice
[hr]
[q]FoxTrick 0.15.0 svn - Stage: true - Skin: normal - lt - ltr - 1852 x 1080 - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.76 Safari/537.36 - Linux x86_64[/q]

**Comment by minj** [comment]
After a lot of hacking managed to do something in dev tools:
![frozen columns](https://cloud.githubusercontent.com/assets/1035523/10265606/e385a90c-6a3f-11e5-8079-5ac913f1dcd1.png)

**Comment by minj** [comment]
Unfortunately doesn't work in FF:
![Firefox frozen](https://cloud.githubusercontent.com/assets/1035523/10265668/cff7127e-6a42-11e5-89c4-e499260d24aa.png)

**Comment by minj** [comment]
Managed to work something out with absolute positioning: ![Firefox absolute froze](https://i.imgur.com/0lMT3DI.png)

**Comment by minj** [comment]
Rendering works:
![frozen columns](http://i.imgur.com/W8bperU.png)

Other logic will be a pain though

**Comment by SparKot** [comment]
Apparently, yellow row-highlighting is broken. 
Mouse-Over rows are not highlighted when Freeze-Columns is disabled.

**Comment by minj** [comment]
so it seems, thanks
