### ISSUE TITLE
Update event icons in MatchReportFormat

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1286]
**From:** llramone_nonumber
**PostID:** [16751289.23](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16751289%26n%3D23%26v%3D0)
**To:** Everyone
**Re:** [16751289.1](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16751289%26n%3D1%26v%3D0)
**Datetime:** 2015-03-19 10:51
**Message:**

I cant see the Reorganize and Nerveous icons at Match Report, check minutes 90 and 83 on this match [(5924940)](https://www.hattrick.org/goto.ashx?path=%2FClub%2FMatches%2FMatch.aspx%3FmatchID%3D5924940%26sourceSystem%3DHTOIntegrated)
Cache cleared, all the others icons are working fine, should I do something else?

Thanks!

---
> FoxTrick 0.14.0.3 release mozilla - Stage: false - Skin: normal - en - ltr - 1280 x 773 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:36.0) Gecko/20100101 Firefox/36.0 - MacIntel

**Comment by minj** [comment]
current icons: https://github.com/minj/foxtrick/tree/master/content/resources/img/matches

**Comment by minj** [comment]
[Event descriptions](https://github.com/minj/foxtrick/blob/master/content/util/match-event.js#L280)
[Icon definitions](https://github.com/minj/foxtrick/blob/master/content/util/match-event.js#L207)
[Event<->icon map](https://github.com/minj/foxtrick/blob/master/content/util/match-event.js#L31)

**Comment by ratsrats** [comment]
I sure like to support Foxtrick. Give me some time, I'll look in to the subject : )

**Comment by ratsrats** [comment]
"There are quite a few match events that could benefit from additional icons."

I could not make up for which match events new icons are to be made. 
From browsing the list img/matches, there appear to be a lot of different sizes for icons. 

1. Could you supply me with a list of events that need an icon?
2. What are minimal and maximum measurements for the icons?

**Comment by minj** [comment]
```
	22: 'Incomplete lineup, players from neighborhood used',
	25: 'Regional derby',
	26: 'Neutral ground',
	27: 'Away is actually home',
	30: 'Spectators/venue - rain',
	31: 'Spectators/venue - cloudy',
	32: 'Spectators/venue - fair weather',
	33: 'Spectators/venue - sunny',
	45: 'Half time results',
	46: 'Hat-trick',
	60: 'Underestimation',
	63: 'Remove underestimation on break',
	64: 'Reorganize',
	66: 'Decrease underestimation on break (equal score)',
	67: 'Decrease underestimation on break (up by 1 goal)',
	69: 'Remove underestimation',
	72: 'Extra time decided',
	80: 'New captain',
	81: 'New set pieces taker',
	331: 'Tactic Type: Pressing',
	332: 'Tactic Type: Counter-attacks',
	333: 'Tactic Type: Attack in the middle',
	334: 'Tactic Type: Attack on wings',
	335: 'Tactic Type: Play creatively',
	336: 'Tactic Type: Long shots',
	343: 'Tactic: Attack in the middle used',
	344: 'Tactic: Attack on wings used',
	500: 'Both teams walkover',
	501: 'Home team walkover',
	502: 'Away team walkover',
	503: 'Both teams break game (2 players remaining)',
	504: 'Home team breaks game (2 players remaining)',
	505: 'Away team breaks game (2 players remaining)',
	700: 'Event-o-Matic: Taunt Opponent',
	701: 'Event-o-Matic: Praise Opponent',
	702: 'Event-o-Matic: Plead for Fan Support',
	703: 'Event-o-Matic: Build Positive Atmosphere',
	704: 'Event-o-Matic: Honour Club Legacy',
```
These are missing. I'm not sure each and every one of them needs an icon though. I'll leave that to your discretion. Any addition is good obviously. 

As for the sizes: there are no standards there as usual :D I see 12x12, 14x14, 16x16, even 19x16. I'd say we should be going for 16x16. Or 20x16 if you need a wider icon.

**Comment by ratsrats** [comment]
Browsing through offered lists I encountered:

bruised: '/Img/Icons/bruised.gif',

I was not able to find this icon. There is an icon folder, in lower case. The uppercase Icon folder is not visible to me. I would like to see some icons before continuing. 

The 'tacticType' icons will be the first to take on.

**Comment by minj** [comment]
FT icons are only where you see Foxtrick.resourcePath.
Otherwise we reuse HT icons: https://www.hattrick.org/Img/Icons/bruised.gif ;)

2015-05-11 12:55 GMT+03:00, ratsrats <notifications@github.com>:

**Comment by ratsrats** [comment]
![aim](https://cloud.githubusercontent.com/assets/5188518/7563148/911f0352-f7da-11e4-9232-cc39bf6514f6.png)
![aim used](https://cloud.githubusercontent.com/assets/5188518/7563151/96bda75a-f7da-11e4-8dab-bf63da0750bc.png)
![aow](https://cloud.githubusercontent.com/assets/5188518/7563154/9daba9e0-f7da-11e4-81f7-cfde90873b5b.png)
![aow used](https://cloud.githubusercontent.com/assets/5188518/7563156/a13894e2-f7da-11e4-9364-cb00ef56479f.png)

These are the first suggestions.

**Comment by ratsrats** [comment]
Suggestions for:
aim
aim used
aow
aow used

**Comment by minj** [comment]
Are you sure they need to be different?
I'd prefer the ones corresponding to 'used' for both cases

**Comment by ratsrats** [comment]
That's all right ; )

**Comment by ratsrats** [comment]
here are some more:

![play creatively](https://cloud.githubusercontent.com/assets/5188518/7566014/d6512882-f7f4-11e4-9d3f-2fd589910317.png)
![counter attack](https://cloud.githubusercontent.com/assets/5188518/7566020/de3afbc2-f7f4-11e4-980d-fd1b2e69b73e.png)

icon play creatively
counter attack

**Comment by ratsrats** [comment]
here are some more:

![counter attack 2](https://cloud.githubusercontent.com/assets/5188518/7566830/63b3d5a4-f7f9-11e4-98bc-f2c75b2862d5.png)
![longshot](https://cloud.githubusercontent.com/assets/5188518/7566833/6aee1140-f7f9-11e4-938d-08f35dd3d4b3.png)

icon counter attack
icon longshot

**Comment by ratsrats** [comment]
here are some more:

![pressing 20 px](https://cloud.githubusercontent.com/assets/5188518/7567170/9edd8f92-f7fb-11e4-802a-a75cead757d6.png)
![pressing 30 px](https://cloud.githubusercontent.com/assets/5188518/7567174/a12a2332-f7fb-11e4-8e95-7ea27dbf22d7.png)
![pressing 1](https://cloud.githubusercontent.com/assets/5188518/7567179/aa1915a2-f7fb-11e4-9934-498d9fb160d8.png)

icons pressing

**Comment by ratsrats** [comment]
her is an other one:

![magic wand 2](https://cloud.githubusercontent.com/assets/5188518/7567430/47f59ab0-f7fd-11e4-83aa-9b513f5b8d5a.png)

icon play creatively 2

**Comment by ratsrats** [comment]
here is an other one:

![pressing 3](https://cloud.githubusercontent.com/assets/5188518/7567767/1b81e694-f7ff-11e4-8054-bd02626835b8.png)

icon pressing 3

**Comment by minj** [comment]
It's a bit unclear to me what these are supposed to symbolize:
![](https://cloud.githubusercontent.com/assets/5188518/7566830/63b3d5a4-f7f9-11e4-98bc-f2c75b2862d5.png)
![](https://cloud.githubusercontent.com/assets/5188518/7566020/de3afbc2-f7f4-11e4-980d-fd1b2e69b73e.png)
![](https://cloud.githubusercontent.com/assets/5188518/7567174/a12a2332-f7fb-11e4-8e95-7ea27dbf22d7.png)

as for the muscle, I think it would be clearer if it was rotated ~90deg CW

**Comment by ratsrats** [comment]
![counter attack 2](https://cloud.githubusercontent.com/assets/5188518/7568110/42aea714-f801-11e4-9a15-84c9cc9b9634.png)

Before playing CA, you have to build a wall, to stop the attack : )
In Germany, building a wall or producing concrete is synonym for building a strong defense. In England one defender is called Ronny Concrete for the same reason.

![pressing 5](https://cloud.githubusercontent.com/assets/5188518/7568351/943484ae-f802-11e4-87d9-dd20df0725a7.png)

pressing 5

**Comment by minj** [comment]
I wanted to nudge you a bit :smile: 

I would prefer to have these icons for next version since this requires no code changes and should be failproof.

E. g. icons are definitely needed for events that effect ratings (like [underestimation](https://www.hattrick.org/goto.ashx?path=%2FClub%2FManager%2F%3FuserId%3D145648%26browseIds%3D))

**Comment by minj** [comment]
@ratsrats If you don't have the time, just say so. It's fine.

**Comment by ratsrats** [comment]
@minj you must have fallen of the radar.

**Comment by ratsrats** [comment]
Would you be so kind to produce a list of icons that are due:

underestimation
 . .

size will be: 20x20 px

**Comment by minj** [comment]
I think these are most important:
```
25: 'Regional derby',
26: 'Neutral ground',
60: 'Underestimation',
63: 'Remove underestimation on break',
64: 'Reorganize',
66: 'Decrease underestimation on break (equal score)',
67: 'Decrease underestimation on break (up by 1 goal)',
69: 'Remove underestimation',
```

Those remove/decrease underestimation could be the same icon obviously

**Comment by ratsrats** [comment]
I will have a go at these.

**Comment by ratsrats** [comment]
![reorganise _ 01](https://cloud.githubusercontent.com/assets/5188518/8374751/4cda515a-1bf8-11e5-8fff-2ae88b4e7e68.png)
![decrease underestimation _ 01](https://cloud.githubusercontent.com/assets/5188518/8374752/4cdedf90-1bf8-11e5-8404-d5d9b1aa1dd8.png)
![remove underestimation _ 01](https://cloud.githubusercontent.com/assets/5188518/8374753/4ce619e0-1bf8-11e5-9557-13b174798aa8.png)
![underestimation _ 01](https://cloud.githubusercontent.com/assets/5188518/8374754/4ceed440-1bf8-11e5-8a3f-71633a079de6.png)
![neutral ground _ 22](https://cloud.githubusercontent.com/assets/5188518/8374755/4cf5c926-1bf8-11e5-95bf-66a5fd408e9b.png)
![regional derby _ 22](https://cloud.githubusercontent.com/assets/5188518/8374756/4cfce59e-1bf8-11e5-9ff3-ae5ea253059b.png)

**Comment by ratsrats** [comment]
from top to bottom:

reorganise
decrease underestimation
remove underestimation
underestimation
neutral ground
regional derby

**Comment by minj** [comment]
Cool thanks, I'll include them in new release soon. I'll also add you to our contributor list as a designer

**Comment by ratsrats** [comment]
thank you, the pleasure is all mine.
