### ISSUE TITLE
Add a button to remove teams from currency list

### ISSUE THREAD

**Issue by tesser57** [minj/foxtrick#1292]
Hello
During setup it says a team that I know nothing.
Team 1746554 I do not own but have had a team in cyprus

**Comment by minj** [comment]
1746554 is Hattrick team ID. It refers to [EVAGORAS (1746554)](https://www.hattrick.org/goto.ashx?path=/Club/?TeamID=1746554), a team in Cyprus.

Is that not your team?

**Comment by tesser57** [comment]
No team 1746554 Evagoras is not my team. I have a 1 team in Denmark and my
2 team in Kuwait.
Be fore i have a team in cyprus.
I can only have 2 team in Hattrick.

Hans-Henrik Thestrup
Den 13/04/2015 22.51 skrev "LA-MJ" <notifications@github.com>:

**Comment by minj** [comment]
Just to clarify, you are talking about this section, right?
![currency_table](http://i.imgur.com/o94U094.png)

I have no idea how some other team could get on that list. Perhaps somebody else used your browser or you imported somebody else's settings?

In any case, it has no harmful effects for you. I'll add a button to remove teams in next release.

**Comment by tesser57** [comment]
Yes, this is  the section i am talking about.

 



 

So you cant see, team 1746554 is not my team, i have before a team in cyprus.

SO i dont where this team stay here.

 

 

Fra: LA-MJ [mailto:notifications@github.com] 
Sendt: 14. april 2015 11:48
Til: minj/foxtrick
Cc: tesser57
Emne: Re: [foxtrick] Setup i foxtrick 0.15.0 (#1292)

 

Just to clarify, you are talking about this section, right?
 <https://camo.githubusercontent.com/a8400e7b1b6bd9e977859f96e2888be0896b320f/687474703a2f2f692e696d6775722e636f6d2f6f3934553039342e706e67> currency_table

I have no idea how some other team could get on that list. Perhaps somebody else used your browser or you imported somebody else's settings?

In any case, it has no harmful effects for you. I'll add a button to remove teams in next release.

**Comment by minj** [comment]
the button will be added when 0.15.1 is released
