### ISSUE TITLE
Form update not taken into consideration for position contribution

### ISSUE THREAD

**Issue by end-er** [minj/foxtrick#1295]
Hello, I noticed that after the training update the contribution displayed for positions remained unchanged for players that gained or lost one level in form. I have Include form into calculations checked under PlayerPositionsEvaluations. 

FoxTrick 0.15.0 release safari - Stage: false - Skin: normal - en-GB - ltr - 1280 x 717 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/7.1.5 Safari/537.85.14 - MacIntel

**Comment by minj** [comment]
**From:** LA-MJ
**PostID:** [16796227.89](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16796227%26n%3D89%26v%3D0)
**To:** whiskas31
**Re:** [16796227.83](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16796227%26n%3D83%26v%3D0)
**Datetime:** 2015-04-17 07:52
**Message:**

I cannot confirm.

Form on:

[(http://i.imgur.com/yfYTRKt.png)](http://i.imgur.com/yfYTRKt.png)

[![Įkeltas paveikslėlis](http://i.imgur.com/yfYTRKt.png)](http://i.imgur.com/yfYTRKt.png)

Form off:

[(http://i.imgur.com/goIs920.png)](http://i.imgur.com/goIs920.png)

[![Įkeltas paveikslėlis](http://i.imgur.com/goIs920.png)](http://i.imgur.com/goIs920.png)

Obviously, only players with form < 8 are affected. Check PlayerPositionsEvaluations again

**Comment by minj** [comment]
Are you still affected?

You could try these steps:

> **Get the FoxTrick log**
> Visit the page you are having trouble and use the bug report link
> ![](http://i.imgur.com/yEhsWmG.png)
>
> Follow instructions that appear.

**Comment by minj** [comment]
I think I misunderstood the problem. If this is regarding SkillTable instead, it may be due to stale CHPP cache. However, this shouldn't happen any more as the system was rewritten.

In the absence of more information I will close this issue. Please report if the problem remains and provide a better explanation
