### ISSUE TITLE
Show correct cup icons in MyMonitor

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1297]
CupA, CupB, CupC according to CupLevel
added in [matches.xml version 2.8](https://www.hattrick.org/goto.ashx?path=%2FCommunity%2FCHPP%2FNewDocs%2FFile.aspx%3Fname%3Dmatches)

**Comment by minj** [comment]
I wonder if simple series page icons like ![](https://stage.hattrick.org/Img/Icons/cupB.jpeg) should be used for all cupBs or the full icons (with colors) like in matches list

**Comment by murko69** [comment]
If I have a vote in this I would rather see "full color" like in the matches list and not just the grey version of the cupBs that appear in the leagues,
