### ISSUE TITLE
Not able to Copy Ratings

### ISSUE THREAD

**Issue by masteradhoc** [minj/foxtrick#1304]
HI there

Its not actually saving the Ratings for my match next saturday temporarily to be inserted via CMD and V..
Mac OS 10.7.5, Foxtrick on Safari
http://pastebin.com/SKp19G9A

Any known issue?

**Comment by minj** [comment]
You mean the copy ratings button in match simulator? Nobody complained until now.

The problem is I don't have a Mac and copying does not work at all in a VM.

By the way, 0.15.1 is the current version, you are behind, get it from https://www.foxtrick.org/download

**Comment by masteradhoc** [comment]
Yes the Copy Ratings Button! I'll try it today again with 0.15.1 and also with a restart ot the macbook

**Comment by masteradhoc** [comment]
Now i'll got the Update of Foxtrick! Now it all works again..
