### ISSUE TITLE
Ease search for next youth league

### ISSUE THREAD

**Issue by reineckef** [minj/foxtrick#1328]
I think the process to _find a new youth league_ `/Search/?view=youthseries` annoying and tedious if the start date is important. **Filters** to only show leagues with certain criteria (start within the next x days, minimal y and maximal z free slots in league etc) and proper **sort functions** would be fantastic! The current sort funtion in Hattrick is by league-name (totally meaningless), and filters are only per country or by size of league (number of teams), which is a start - but far from useful! Also, the number of leagues shown per page is low - and sort on sublists is buggy (start date sort does not work reliably).

Thanks for all the great work! Keep it up!

**Comment by minj** [comment]
We cannot increase the number of leagues shown. Without that extra information there is little that can be done to make one's life easier. Unless you have more ideas @reineckef?

I'll keep the issue open but it's low priority.

**Comment by minj** [comment]
Apparently you can use the search even in the middle of the season.

Now that I looked at it, I think filters could be done by simply hiding leagues that don't match. However sorting is impossible like I said. Unless you think visiting all 16 (at the moment) pages manually (as in by the user), and collecting the data first is a good idea.

**Comment by reineckef** [comment]
Thanks for considering this. I did not get your message: Could Foxtrick gather all 16 pages in the background and make one big final table, filtered and properly sortable by date? That would solve this, and would be awsome. I have no idea how tricky it will be to have someone at Hattrick increase the number of results per page - could make things easier for you, and maybe also reduce server load at Hattrick. Thanks again.

**Comment by SparKot** [comment]
This one is tricky one.
1. **FoxTrick Collects data from all 16 pages** :-1: : that's multiplying the load on HT by 16 times.
2. **FoxTrick sorts results by _first match date_ Ascending** :+1: : FoxTricks is playing with HT returned results.
3. **FoxTrick filters results based on _available slots_**:+1: : FoxTricks is playing with HT returned results. Also helps friends coming together to join a youth-league for extra fun; as they looking for specific number of open/available slots.

That's doing without any extra load on HT-servers; perhaps like Transfer-Listing pages.
cheers

**Comment by reineckef** [comment]
I understand pulling all the pages will increase the load for HT. But, you could argue that this is just pre-loading pages a user would load anyway himself, while searching - a few seconds later. Maybe not all, though. 

Anyway, improving on sort functions for free slots and dates and adding filters for free slots (could also comprise dates, e.g. latest start or so) would make a big improvement without adding more load to HT. Yes, it is similar to custom transfer filters (e.g. for specialty). 

Thanks! Any help appreciated!

**Comment by minj** [comment]
@reineckef It's not about the load. CHPP license prohibits us to crawl HT pages automatically. We can only use:
- a) information already available in HTML 
- b) what is available from CHPP interface

Those data do not fall into either of the categories. There's a search API in CHPP but as luck would have it it does not include anything youth-related. Everything else from the [search page](https://www.hattrick.org/goto.ashx?path=%2FSearch%2F) is available. I'll file a CHPP bug.

The only option for now is to let the user browser all pages manually and build the table as info comes in. The same principle is used in [team history page](https://www.hattrick.org/goto.ashx?path=%2FClub%2FHistory%2F%3FteamId%3D672194) (HistoryStats module)

**Comment by reineckef** [comment]
Ah, ok, I see. Fully understand. But having my browser hide things not matching what I am looking for is also better than nothing ;o). It is fine if I need to click "next page" myself (all over) until some results show up that match my filter. 

Thanks for all the work you guys do.

**Comment by minj** [comment]
HTs now sort it by start date

**Comment by reineckef** [comment]
I have seen it, great change by HT imho.
