### ISSUE TITLE
Add playedInTeam matches count if/when available in CHPP/DOM

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1330]
There was some testing on stage related to this, I think

---

**From:** CAT-esperitdelbosc
**PostID:** [16412248.479](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16412248%26n%3D479%26v%3D0)
**To:** Everyone
**Re:** [16412248.1](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16412248%26n%3D1%26v%3D0)
**Datetime:** 2015-10-07 16:06
**Message:**

Hi

one day I proposed the current yellow shadow for the team players table, which Is very useful.

So I suggest if it would be possible to add the avaiability to add a "matches played in club" column, that would be very interesting to have the info in the table, to see the oldest players etc... I dunno if it's easy.

Thanks!

---

> FoxTrick 0.15.2.1 hosted chrome - Stage: false - Skin: normal - ca - ltr - 1440 x 860 - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36 - Win32

**Comment by minj** [comment]
**From:** LA-MJ
**PostID:** [16582160.259](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16582160%26n%3D259%26v%3D0)
**To:** HT-Gusy
**Re:** [16582160.183](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16582160%26n%3D183%26v%3D0)
**Datetime:** 2016-05-02 00:30
**Message:**

> HT-Gusy rašė:
>
> We've released 2 small but nice features to Stage:
>
> • Player salary history, found as a link under More info in the player details page. We started collecting the data around 5 seasons ago, so that's as far as it goes.
>
> • Goals for current team, found in the Goals section of the player details page.
>
> Please have a look and let me know if you find any issues.
>
> Thanks and enjoy! :)

CHPP support seems neglected these days. Could we at least have the goal counter please?

**Comment by ventouris** [comment]
From the request list, the following will be available on the next build

players:
GoalsCurrentTeam 
ArrivalDate
OwnerNotes 
matchesCurrentTeam.

**Comment by minj** [comment]
Both files seem to be bugged. An entry in the change log exists and one can try selecting the new version in docs. However no actual info on those new fields exist in the docs.

What is worse, the new version is not recognized (default is returned) both in Example app and in FT.

When do those CHPP builds occur exactly?

**Comment by ventouris** [comment]
I never built the new version. Doing it now.
