### ISSUE TITLE
Match simulator feature doesn't work

### ISSUE THREAD

**Issue by Marini78** [minj/foxtrick#1348]
What steps will reproduce the problem?
-> Go to line up and press rating forecast

What is the expected behaviour? What is the actual behaviour instead? You
could provide a screenshot if necessary.

-> Should be some ratings visible, but the detail ratings are not visible (no total scores)
What is the version of the FoxTrick, your browser and operating system?

-> 0.13.0.1 release mozilla

-> Debug information
Version 0.11.0.2 hosted chrome, Sandboxed Chrome platform, ru locale, standard layout, run time:  358  ms |  /Club/Matches/MatchOrder/ ?MatchID=546548071&SourceSystem=Hattrick&teamId=1016615
 ApiProxy: options:  {"cache_lifetime":"session"}   cache_lifetime:  session   current timestamp:  Mon Oct 26 2015 22:14:00 GMT+0100
 ApiProxy: use cached xml:  [["teamId",1016615],["file","players"],["version","2.2"],["includeMatchInfo","true"],["showLastMatch","true"]]
 hasPlayerInfo
 interface ready:  true
 hasInterface
 uncaught error in listener Node was not found
: 202
Stack trace:
chrome://foxtrick/content/matches/match-simulator.js:202:1
chrome://foxtrick/content/util/dom.js:183:5

 uncaught error in listener Node was not found
: 202
Stack trace:
chrome://foxtrick/content/matches/match-simulator.js:202:1
chrome://foxtrick/content/util/dom.js:183:5

 tab focus: 3
 tab focus: 2
 tab focus: 4
 tab focus: 5
 tab focus: 4
 tab focus: 5
 tab focus: 4

->Please provide any additional information below.

**Comment by minj** [comment]
Get the latest version from https://www.foxtrick.org/download
