### ISSUE TITLE
Incorrect settings on version 0.16.0 on Mozilla 44.0.a2

### ISSUE THREAD

**Issue by eyp** [minj/foxtrick#1349]
Foxrtrick detected Sweden, but I'm on in Belgium. Language and date format is ok.

**Comment by minj** [comment]
Sorry I somehow missed an email notification for this issue.

44.0.a2 was that aurora or nightly?

In any case FT does not support multi-process yet. You must disable it to use Foxtrick

**Comment by eyp** [comment]
Aurora

**Comment by minj** [comment]
So, does the issue remain with multi-process disabled?

**Comment by minj** [comment]
@eyp does the issue remain with e10s disabled?

**Comment by eyp** [comment]
No, with e10s disabled it works

**Comment by minj** [comment]
Alright, then. #1337 is for e10s
