### ISSUE TITLE
HTMS points fail with divine+ skills breaking SkillTable, match report and match order interface

### ISSUE THREAD

**Issue by kupteri** [minj/foxtrick#1392]
When viewing last match most of my players seems to be "sold" and their specialities aren't shown. Only players 1, 2 and 3 are ok.

[http://pastebin.com/L6xujMuC](http://pastebin.com/L6xujMuC)

![bug1](https://cloud.githubusercontent.com/assets/18010958/13957658/dc04c702-f055-11e5-81fe-5ea90e7998db.png)

Same bug occurs when trying to set lineup for next match. Specialities and last match information is shown only for first two players. Third player shows "Undefined" and next ones nothing.

[http://pastebin.com/1aG1E15s](http://pastebin.com/1aG1E15s)

![bug2](https://cloud.githubusercontent.com/assets/18010958/13957701/1217a62a-f056-11e5-9456-366626115454.png)

This problem happens only with my first team. Second team is ok.

I have updated newer version of Foxtrick (official and beta), restarted, inactivated Foxtrick, cleared all caches, restarted, reactivated Foxtrick but nothing helps.

Feels like something happens after fetching my third player's info.

Please help me.

**Comment by minj** [comment]
This is related to the fact that your players have skills above divine, SP most likely.

This breaks HTMS point calculation that cascades down into other issues. We have not yet decided what to do with HTMS points for divine+ skills...

**Comment by kupteri** [comment]
Thanks for analysis! Indeed I have several players divine+1 and divine+2 in SP and I'm still training them.

**Comment by taised** [comment]
These are the new values for skills up to 23. If you see that some values are just the same for higher levels it's ok, since we do not have values for those skill as we haven't found anyone (and probably it is not possible) to reach those values. Anyone who can push it, please do it.


		pointsSkills[21] = [1074, 1791, 1791, 1172, 1355, 1547, 334];
		pointsSkills[22] = [1278, 1791, 1791, 1360, 1355, 1547, 388];
		pointsSkills[23] = [1278, 1791, 1791, 1360, 1355, 1547, 450];

**Comment by minj** [comment]
@taised done, new build should be out in ~10min

**Comment by kupteri** [comment]
Tested and verified with 0.16.11.445 beta version in Firefox. Now this works. Thanks!
