### ISSUE TITLE
Can't see transfer list

### ISSUE THREAD

**Issue by kezara** [minj/foxtrick#1394]
I receive blank page as a search result of players transfer listed. I receive info that have certain number of pages with players on list but no players to be selected, just blank page with info about supporter and skills table. Result page attached. Foxtrick version 0.16.1.1 hosted chrome. win 8.1 x64, chrome 49.0.2623.87 m
![untitled](https://cloud.githubusercontent.com/assets/18076352/14053029/e3afbb4e-f2ce-11e5-9bb7-25d1e682c719.png)

**Comment by minj** [comment]
Please search among the closed issues before submitting new ones. See #1387 and #1390

**Comment by minj** [comment]
fixed in 0.17.0
