### ISSUE TITLE
Foxtrick may be disabled in Firefox due to bad signature

### ISSUE THREAD

**Issue by OpeningBat** [minj/foxtrick#1397]
I'm guesing the foxxtrick add-on is unsigned, hence Firefox is automatically disabling the add-on. More details here https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct 

Is there any chance you can get the add-on signed by Mozilla?

Cheers,
Mick

**Comment by minj** [comment]
Ir IS signed. Which version do you use?

**Comment by OpeningBat** [comment]
I’m using 0.16.1.1 (Windows 10). 

Since you said it is signed, I delete my cached web content in Firefox, restarted my laptop and installed foxtrick again. Now foxtrick is working.

Previously, if I downloaded/installed foxtrick then it would work for that session, but after shutting down and restarting Windows then it would stop working again,. After clearing my cached web content I have shutdow n and restarted twice and foxtrick is still working . When it wasn’t working, then if I clicked on Tool->Add-ons then foxtrick would be listed under “Extensions” and showing as Disabled; now that foxtrick is working it is not showing in “Extensions”. 

Hopefully this is now fixed for good. 

Thanks for your quick reply. 

Cheers,
Mick

**Comment by minj** [comment]
This might happen if some outside process modifies Foxtrick files on your PC. This would break FT signature and disable it.

This maybe a sign of malware or something more benign: ccleaner, antivirus, some backup service etc.

I'll try to modify FT distribution to make such changes more difficult in the future but first there are some issues to take care to make that happen
