### ISSUE TITLE
Match prediction problem - Problema en prediccion de partido

### ISSUE THREAD

**Issue by yonaviseiro** [minj/foxtrick#1399]
Hi guys, I have a problem with FoxTrick and 2 weeks ago. it turns out that when assembling the team for the next official league match, when I select "prediction performance" and put any official last 4 league games of my opponent does not make me prediction. When I put the equipment I use in recent friendlies or 5th if you do, but the last 4 official does not .. anyone know what happened?- Now remove and install again FoxTrickAny solution ?It will go off any feature specified in preferences FoxTrick?

-------

Hola muchachos, tengo un inconveniente con FoxTrick hace ya 2 semanas. resulta que al momento de armar el equipo para el próximo partido oficial de liga, cuando selecciono "predicción de rendimiento" y pongo alguno los últimos 4 partidos oficiales de liga de mi rival no me hace la predicción. Cuando pongo el equipo que utilizo en amistosos o de los últimos el 5to si lo hace, pero con los últimos 4 oficiales no lo hace.. Alguien sabe que paso?
- Ya elimine y volví a instalar foxtrick
Alguna solución ? 
Se ira desactivado alguna característica especifica en preferencias de foxtrick?

**Comment by minj** [comment]
Do you have players with skills above divine?

**Comment by yonaviseiro** [comment]
no no

**Comment by minj** [comment]
Like I've told you on HT, I need the Foxtrick log

---
**From:** LA-MJ
**PostID:** [16955983.2](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16955983%26n%3D2%26v%3D0)
**To:** yonaviseiro
**Re:** [16955983.1](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16955983%26n%3D1%26v%3D0)
**Datetime:** 2016-04-07 11:09
**Message:**

> **Get the FoxTrick log**
> Visit the page you are having trouble and use the bug report link
>
> ![](http://i.imgur.com/yEhsWmG.png)
>
> Follow instructions that appear.

**Comment by minj** [comment]
I need your feedback to make progress with this issue.

**Comment by minj** [comment]
Closing this issue due to lack of feedback. 

Get the latest release from https://www.foxtrick.org/download

If the problem persists, please open another issue
