### ISSUE TITLE
Match Order Interface : Loyalty of players

### ISSUE THREAD

**Issue by SparKot** [minj/foxtrick#1400]
**Soft - Error**
On match order interface when mouse over between players with two different loyalties, soon orange (HG, loyalty) colours mess up.

e.g. 
A - player with divine loyalty
B - player with weak loyalty

After a couple of mouse overs:

http://easycaptures.com/fs/uploaded/898/3200339710.jpg

[hr][spoiler]Foxtrick 0.16.11.412 beta-09fae16 mozilla - Stage: false - Skin: normal - en-US - ltr - 1366 x 740 - Mozilla/5.0 (Windows NT 5.1; rv:42.0) Gecko/20100101 Firefox/42.0 - Win32[/spoiler]

**Comment by minj** [comment]
I cannot confirm. Your Firefox is behind by a few versions. Try updating.

**Comment by minj** [comment]
any progress?

**Comment by minj** [comment]
Closing this issue due to lack of feedback.

Get the latest release from https://www.foxtrick.org/download

If the problem persists, please open another issue
