### ISSUE TITLE
New HT-Live pop-up z-index issue

### ISSUE THREAD

**Issue by Mandlee** [minj/foxtrick#1446]
There is something trouble with z-index in new HT-Live for supporters. Without Foxtrick the pop-up is display expeceted with z-index: 110;

<img width="1440" alt="kepernyofoto 2016-10-28 - 8 42 27" src="https://cloud.githubusercontent.com/assets/6671787/19798329/a0727552-9cf0-11e6-9cc8-99e97e82f781.png">

**Comment by minj** [comment]
Yes, I noticed that as well

**Comment by minj** [comment]
However, I dismissed it on HT with FT disabled and can no longer figure out what's wrong.

Do you still have it? Outer HTML of `div.ng-scope[ng-if="browserHasNotifications()"]` would be useful. I think

**Comment by minj** [comment]
closed due to lack of reproducibility (and feedback)
