### ISSUE TITLE
Foxtrick cannot detect my team on hattrick

### ISSUE THREAD

**Issue by Lupacciok17** [minj/foxtrick#1483]
Hi, I installed the extension Foxtrick 0.17.0.1 on browser Firefox 51.

When I open hattrick.org page and log on I cannot detect my team, so cannot authorize the CHPP product for the access to datas.
Looking on foxtrick preferences by the link on the add-on extension page the informations are wrong. (it detects sweden and cannot insert my team.

How to let it work properly? Or better, how to let it start detect my team when I log on hattrick.org?

Thanks,
LKS

**Comment by minj** [comment]
**From:** LA-MJ
**PostID:** [16963779.354](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16963779%26n%3D354%26v%3D0)
**To:** thom_raindog
**Re:** [16963779.344](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16963779%26n%3D344%26v%3D0)
**Datetime:** 2017-01-29 21:50
**Message:**

Now... If you have multi-browser enabled (also known as "Foxtrick completely gone") strictly follow these steps:

1) type about:config as web address and press enter

2) press "I will be careful, I promise", if such message is visible

3) search for "browser.tabs.remote.autostart" and double click on any value that says "true" (to set it as "false" which we want)

4) press shift+F2

5) type "restart" and press Enter

6) enjoy

**Comment by Lupacciok17** [comment]
Hi, thanks for answer.
Nice trick but it didn't work.

Looking by the about:config table I could fine a lot of string sequence like:
extensions.foxtrick.prefs.htCountry
from which I can set the variable (true/false) or code (ex Italy, en)

By double-clicking I could change a code or variable and I set the country (string: extensions.foxtrick.prefs.htCountry).
Do you think I can set manually one of this codes to let detect my team and give the authorization to Foxtrick CHPP program?

Thanks in advance,
LKS

**Comment by minj** [comment]
You incorrectly assume that my instructions were not exact.

The fact that 'country is not detected' is only a consequence of the fact that Foxtrick is completely broken when multi-process is enabled in Firefox.

Now, instead of editing various Foxtrick preferences by hand which will lead you nowhere, reread what I posted again and follow the instructions to the letter.

**Comment by minj** [comment]
see #1493
