### ISSUE TITLE
How to enable Foxtrick!?

### ISSUE THREAD

**Issue by SharakPL** [minj/foxtrick#1493]
I must be blind, because there's absolutely no info on how to even enable this. I've been using Foxtrick for years and I remember it always checked for my language preferences and used it automatically. It also showed info on activating, using HT's CHPP etc. I've just updated my browser and refreshed it so I had to install all my addons again, but Foxtrick does absolutely nothing. Doesn't update my lang, country or currency. Doesn't show anything on how to enable it. Why there's no info about it on the homepage? There always should be a tutorial about installing and activating, because it's sooooo irritating :/

**Comment by SharakPL** [comment]
https://www.hattrick.org/Forum/Read.aspx?t=17065768&n=1&v=6
Not everyone is using Foxtrick's specific forum on HT. This information should be also **on the homepage** where you get foxtrick from! Don't you think?

> If you have multi-browser enabled (also known as "Foxtrick completely gone") strictly follow these steps:
> 1) type "about:config" as web address and press enter
> 2) press "I will be careful, I promise", if such message is visible
> 3) search for "browser.tabs.remote.autostart" and double click on any value that says "true" (to set it as "false" which we want)
> 4) press shift+F2 (or I guess that would be command+F2 on a mac)
> 5) type "restart" and press Enter
> 6) enjoy
> 
> Information about "about:config": (https://support.mozilla.org/en-US/kb/about-co...refox)
> 
> Background information on the root of the problem: (16963779.316)
> Information on multi-process mode: (https://wiki.mozilla.org/E10s)

Fixed

**Comment by minj** [comment]
No, I do not. The information is there for those who look for it, just like you were able to find it. Be it on twitter or forum or my team page or my inbox (yes, nobody reads anything else, it seems).

I do not have the resources to fix the underlying problems in a reasonable time frame and much less to hunt down every FT/FF user and feed them this information against their will, sorry.

If anything, blame mozilla for being a hard-ass with their Electrolysis/webextension push.

**Comment by minj** [comment]
Sorry for the badly executed sarcasm btw. The honest answer is, I just can't get to every place where one would look for information in time. The website would be a logical first choice indeed, if not my actual experience that seems to indicate that noone is actually reading it. Or anything else, for that matter.

Here's a typical scenario in our forum:
A: help, I have no idea what to do!
B: here's how to fix it:...
A: thanks, it worked!
C: help, I have no idea what to do!

**Comment by minj** [comment]
frustrating, to say the least

**Comment by minj** [comment]
link to instructions added

**Comment by SharakPL** [comment]
Sorry if I was too harsh about it, but keeping documentation in the right place should be obvious. You don't get Foxtrick from HT, Twitter, Facebook etc, You get it from your homepage and that's the MAIN place any related information should be stored in. Especially if it's crucial troubleshooting info. 

Thanks for all your hard work :)
