### ISSUE TITLE
[Idea] Tagging (mention) system for forums

### ISSUE THREAD

**Issue by rferromoreno** [minj/foxtrick#1503]
I'd been thinking this for a long time.

Since HT forum isn't a current priority for HT devs, I was wondering if we can do a Tagging (mention) system for the forum.

How could this work?

Supose a BBcode like this

`[tag=userId]`

where _userId_ is any user ID.

While parsing that BBCode, the module should retrieve data from **Manager Compendium** file (on CHPP CPI) and use the **LoginName** attribute.

Then, the parse should be something like this:

`<a class="mention" href="/Club/Manager/?userId=$userId"> $loginName </a>`

(ignore the pseudocode, just think about the idea).

Is this possible? It could be a nice approach. However I think that having lots of mentions on a single page could slow down the load of the page (using async maybe could help, also local-storage to reduce requests for multiple mentions of same user)

What do you think?

**Comment by minj** [comment]
I am slightly confused. How is this better than just having a userid link or conversely writing the username as is?

At first reading this I figured you'd like to implement some sort of ad-hoc notification system :)

Normally, I rejected any suggestions that involve fetching different information via CHPP for (potentially) each and every message on the page.

I remain skeptical about the usefulness here. Care to expand on it?

**Comment by rferromoreno** [comment]
Well, yes and no.

We cannot do much here about notifications. That's all on HT devs.

Anyway, it would be nice to show user LoginName when an user is linked.

So, **userid** and **tag** BBCodes are the same. But **tag** shows the LoginName while **userid** doesn't. Having both bbcodes could be useful when original poster don't want to show the LoginName.

**Comment by minj** [comment]
I am closing this due to lack of usefulness (imho) and issues in implementation:
1. login name is actually secret
2. user alias can change
3. fetching CHPP for (potentially) each message is against my policy (historically, there were cases when we had to change/limit our functionality due to excessive CHPP usage)
