### ISSUE TITLE
Add to pool: Country select displays wrong countries

### ISSUE THREAD

**Issue by mindw0rm** [minj/foxtrick#1513]
The country select shown on the "Add your team to pool" and "Change pool criteria or remove from pool" pages shows wrong countries and/or the ordering is wrong. The country you select is not the country sent to Hattrick (see below).

For example, Andorra is completely missing.
When I disable Foxtrick, select Andorra, re-enable Foxtrick and Revisit the page, Malta is selected. 
This is not only a display problem, since the selected ID is indeed changed.

Other countries are mapped to something else. I first encountered the bug last season, when I was pretty sure that I selected a very specific country and ended with a friendly in some other country (unfortunately I can't remember which countries those where exactly - I think it was India and Albania, but I am not sure any more). I wasn't sure if that maybe was my mistake at that time, but now that I found Andorra completely missing, I made some investigations and narrowed it down to a Foxtrick bug. 

Tested on both stage and non-stage, and also with a fresh profile that contains no other extensions but Foxtrick. Also happens with both en_GB and de_DE (my default) locales. 

The change of the selected country can also be observed when disabling/enabling Foxtrick while the page is open.

Browser: Firefox
Foxtrick version: 	0.17.0.1 release mozilla
[Foxtrick log URL](https://pastebin.com/b5y9r3gY)

**Comment by minj** [comment]
This should be fixed in beta: https://www.foxtrick.org/download/beta
