### ISSUE TITLE
prédiction des notes

### ISSUE THREAD

**Issue by hieros69** [minj/foxtrick#1515]
bonjour,

les prédictions de notes ne fonctionnent plus sur foxtrick. Tout est noté inexistant.

Cordialement

**Comment by ariehead** [comment]
Same issue as I adressed: issue #1516

**Comment by ariehead** [comment]
Don´t know what happened but it is solved !
Please close this issue ..

**Comment by minj** [comment]
sorry, I do not speak French

duplicate of #1516
