### ISSUE TITLE
Foxtrick doesn't show scores on match prediction

### ISSUE THREAD

**Issue by marcodav** [minj/foxtrick#1518]
Dear Foxtrick team, when i am in the panel to select the players for the match and i want to see scores of my players and compare them with the other team players, it only shows the other team players' score.
Here attached a screenshot to explain myself better.

Foxtrick log URL [link=https://pastebin.com/NTqUtyXf]
![schermata 2017-07-15 alle 07 42 02](https://user-images.githubusercontent.com/30191539/28236854-777b8810-6931-11e7-9a0d-b002d392653f.png)

**Comment by ariehead** [comment]
Same issue as #1515  and #1516

**Comment by Fxhappy** [comment]
same problem.

**Comment by ariehead** [comment]
Don´t know what happened but it is solved !
Please close this issue ..

**Comment by minj** [comment]
duplicate of #1516
