### ISSUE TITLE
Wrong source for custom kits on match report -> lineup page

### ISSUE THREAD

**Issue by SharakPL** [minj/foxtrick#1526]
## Short description of the problem
Custom kit's _img_ has wrong _src_ value.
## What steps will reproduce the problem?
Match Report -> Lineups (#tab2). Of course there should be at least 1 team with custom kits.
## What is the expected behaviour? What is the actual behaviour? Please provide any relevant screenshots.
Is for custom kits:
`<img src="/Img/Avatar/res.hattrick.org/kits/25/244/2440/2439380/body7.png">`
... and should be
`<img src="http://res.hattrick.org/kits/25/244/2440/2439380/body7.png">`

**Comment by minj** [comment]
Thanks for the report

**Comment by minj** [comment]
this is actually a CHPP bug

**Comment by minj** [comment]
seems fixed
