### ISSUE TITLE
Foxtrick incompatible with Firefox 57

### ISSUE THREAD

**Issue by Sombreheros** [minj/foxtrick#1540]
Nothing to add or explain. Simply unusable with new firefox 57 version.

**Comment by Jecvay** [comment]
unusable with new firefox 57 version, too!!!

**Comment by minj** [comment]
Sorry guys my personal development machine basically died last week.

I plan to take some time off next week to fix FT.

In the mean time, you can find some test builds @ foxtrick.org/test . NB:
no auto-update

**Comment by Jecvay** [comment]
unbelievable test branch has already support ver57. 
Thanks a lot!

**Comment by helbadini** [comment]
Thanks!

**Comment by minj** [comment]
see https://www.foxtrick.org/download/beta
