### ISSUE TITLE
Show Last U20 World Cup Match in Player/YouthPlayer Details

### ISSUE THREAD

**Issue by rferromoreno** [minj/foxtrick#1542]
Hello all.

I had this idea some time ago and worked over it, however it was stalled due real life responsibilities.

**I already done it. I just have to test it** because I'm not sure if util.time.getHTDate and util.time.toHT are working properly for me, or if I have to normalize dates.

The idea is pretty simple: Having the option players under 20 (also youth players) to check which is the last eligible official match of U20 competitions.

For example:

![untitled](https://user-images.githubusercontent.com/5116187/34912993-103d4a84-f8cf-11e7-8082-6ce4aea50414.png)
![untitled2](https://user-images.githubusercontent.com/5116187/34912994-10a79632-f8cf-11e7-955b-e81969be05c0.png)

I'm just waiting for the idea approval to make the pull request. I know that @minj has a lot of work with WebExt and the Firefox Quantum issues.

Also, this would be a simple version of my module. I think in a future I could add it to the Players page and probably the TransferSearchResult page.

Edit: I also think this idea/issue is something like this #893

**Comment by minj** [comment]
You are right, that's the same issue. I don't see the need for a new one :)

Although, I'll gladly look at that PR, if you still feel like opening it.

**Comment by rferromoreno** [comment]
Glad to read you back again, @minj !

I still have my U20 eligibility module for Foxtrick. How shall I proceed? 

Can I do some questions to you by IRC/Discord/Slack?

**Comment by minj** [comment]
I have an idle znc on our IRC channel so you can ask any time but I'm done for today.

I will come by tomorrow morning CET to answer any questions. It's #foxtrick @ irc.quakenet.org.
