### ISSUE TITLE
NT/U20 managers' flags not updated

### ISSUE THREAD

**Issue by SharakPL** [minj/foxtrick#1543]
Flags for NT/U20 managers are not updated on the forums.

Each national team manager is supposed to be marked with a flag on the forums, but this takes veeeery long to update. At this point managers who aren't NT/U20 managers anymore still have the flags, and new managers don't. Is this a manual process? I cleared cache for browsers and foxtrick, but nothing changed.

BTW. What if someone runs NT in one country and U20 in another? Is he marked with 2 flags?

Also some errors can be seen in report: [https://pastebin.com/v6krGkVF](url)

**Comment by minj** [comment]
should be fixed in a day or two
