### ISSUE TITLE
Match lineup copy ratings and lineup

### ISSUE THREAD

**Issue by battigol9** [minj/foxtrick#1546]
Since the new lineup tool has been introduced I haven't been able to copy the lineup as before as a table I could paste into an HT mail a fed post or what so ever.
Neither is it possible to copy the rating details as a table.

Post match ratings can be copied as before the new lineup tool.

I run Firefox 48.0.2 and Foxtrick 0.17.0.1

I have tried with the tweak "about:config" - no result

**Comment by minj** [comment]
Well, since the tool is not supported, and no one has worked on it, there is no sense wondering why it does not work.

It does not make sense to open tickets for all functions on MatchOrder, there's a bunch. 

#1530 will suffice for now
