### ISSUE TITLE
Wrong Country detect

### ISSUE THREAD

**Issue by RSilentWolf** [minj/foxtrick#1564]

**Comment by minj** [comment]
In curiousity, have you actually visited hattrick before making this screenshot?

**Comment by minj** [comment]
That is quite strange. This bug has been reported time and again but none of the reporters have really engaged to answer any follow-up questions.

Could you please submit a bug report to pastebin anyway?

![bug_link](http://i.imgur.com/yEhsWmG.png)

Please paste the pastebin URL here.

**Comment by minj** [comment]
Another one bites the dust.
