### ISSUE TITLE
Shortcuts disapeared

### ISSUE THREAD

**Issue by RSawkins** [minj/foxtrick#1565]
HI,

My foxtrick in Chrome browser, dont show me anymore the shortcuts.

I've already cleaned cache. dont wort
Remove foxtrick and reinstall. dont work

How can i fix this?

Thank you

**Comment by PeixeAgulha** [comment]
Same here.

**Comment by sole0** [comment]
Same for me and I'm not able to understand what's going wrong

**Comment by minj** [comment]
The service that updates this (and much more) has expired.

I will be restoring this as soon as I find the time

**Comment by minj** [comment]
fixed
