### ISSUE TITLE
REQ- add option to remove HT logo

### ISSUE THREAD

**Issue by mushis** [minj/foxtrick#1567]
Under the option SafeForWork, add an option to remove/replace the hattrick logo (image).
And maybe even replace the green background image.

thx

**Comment by minj** [comment]
SafeForWork module does only things that cannot be done with SkinPlugin. You can do this (and much more) using the latter. Granted, you need to know some CSS.

Sorry but Foxtrick has too many options as it is. Next, I would be getting requests to supply the color value, the image URL, etc etc. And frankly, the TODO list is already endless with plenty of more important tasks.
