### ISSUE TITLE
No me salen ni las caras ni las especialidades de los jugadores en Ht

### ISSUE THREAD

**Issue by Arturoquinter0** [minj/foxtrick#1568]
Estoy teniendo problemas para ver las especialidades de los jugadores en la alineación, ¿que pasa?

**Comment by minj** [comment]
Please submit bugs only in English.

The description is too generic. What page are you trying to access?

Best of all, give me a link to the FoxTrick log:

Visit the page you are having trouble and use the bug report link
![](http://i.imgur.com/yEhsWmG.png)

Paste the pastebin adress here.
