### ISSUE TITLE
Match Analysis Not Loading

### ISSUE THREAD

**Issue by lmack82** [minj/foxtrick#1570]
It seems for the past couple of weeks now, the Match Analysis has given up. It no longer loads when you view the "Predict ratings" screen. Incidentally, if you click the "change prediction" link to load the prediction in HTMS, you can still see the predictions on their site off what Foxtrick pulled up, so there is at least a work-around.

I wasn't sure if this was because I was still using the old match interface, but I've stuck on that since AFAIK, Foxtrick isn't even compatible with the new one yet. In hopes that you had finally switched to being able to run the predictor off the new interface, I checked that out, but it's the same as always... all that's available is HT's own ratings breakdown, but no HTMS prediction. This is literally the only reason I continue to bother with the old match interface... HTMS is a huge factor in my decision-making.

**Comment by minj** [comment]
Discussion about that is @ 16281487.638

**Comment by minj** [comment]
It's a forum message ID

2018-09-15, št, 12:25 Lawrence Mack <notifications@github.com> rašė:

**Comment by Marcolav** [comment]
I'm following this as well.
Please, could you provide a link to the forum message instead of its ID?

**Comment by minj** [comment]
[16281487.638](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16281487%26n%3D638%26v%3D0)

**Comment by minj** [comment]
currently works
