### ISSUE TITLE
Support new HT unified design

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1579]
Zenhub Epic

**Comment by wooheaven** [comment]
I expect this issue will be resolved.
Right now [ new player page ] is not loaded by foxtrick 0.17.0.1

**Comment by minj** [comment]
@woohwaven don't expect to see any progress soon by using that version

Some things are already fixed on player details in https://www.foxtrick.org/download/beta

**Comment by wooheaven** [comment]
Thanks to @minj
I check that it works

**Comment by minj** [comment]
**From:** LA-MJ
**PostID:** [16896702.732](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16896702%26n%3D732%26v%3D0)
**To:** Everyone
**Re:** [16896702.1](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16896702%26n%3D1%26v%3D0)
**Datetime:** 2018-11-01 16:07
**Message:**

**v0.17.9.1026**

We are now into four digit builds. which does not look nice but what can you do, when it's just not ready to be called 'stable'.

---

If you are looking for good news, everything should be working on transfer search, player lists, incl. youth, and player details.

\* There are some differences between stage (which I use now) and production, so your mileage may vary.

Pages that still (may be) broken:

Unmaintained pages: match order, match report, live, forum, ...?

Unsupported 'new' pages: orders, live, new training, tactics room, ...?

Modules that still need work:

- [ ] PlayerStatsExperience
- [ ] ContextMenuCopy
- [ ] OldStyleFace?
- [ ] CountryList?
- [ ] HTDateFormat?
- [ ] LocalTime?
- [ ] FixcssProblems?
- [ ] SimplePresentation?
- [ ] SkillColoring?
- [ ] TeamPopupLinks?

---

This is a depressing list, FT just includes too much...

Let me know if you think you have an issue I don't know about.

**Comment by minj** [comment]
moving away off of ZenHub

remaining work in #1598
