### ISSUE TITLE
Twodigits star rating not parsed

### ISSUE THREAD

**Issue by reineckef** [minj/foxtrick#1607]
The new star layout shows stars in a circle (with stamina). There are two different span classnames, and the "twodigits" version is not parsed at all, leading to ratings of 0 (zero) in the player overview table. 

Example for 12.5 stars:
```html
<span class="stars-full-twodigits">12</span>
<span class="stars-half-twodigits">.5</span>
```
The problem can be fixed in the code referenced here:

https://github.com/minj/foxtrick/blob/308c30f100794e9926e72d75b80ad7610eb5116d/content/pages/players.js#L756-L759

**Comment by reineckef** [comment]
I would fork, fix and leave a pull-request, but I am not very proficient in JS, and I have no way to actually test and validate the proposed fix below. So, I just leave this as a comment for a quick review by a maintainer.

This should do the trick, because either "stars-full" OR "stars-full-twodigits" (same for half) is present:

```js
let fullStars = ratingCircle.querySelector('.stars-full') || ratingCircle.querySelector('.stars-full-twodigits');
let full = fullStars && parseInt(fullStars.textContent, 10) || 0;
let halfStars = ratingCircle.querySelector('.stars-half') || ratingCircle.querySelector('.stars-half-twodigits');
let half = halfStars && parseFloat(halfStars.textContent) || 0;
```
There may be more elegant ways to accomplish the task?

Hope this helps to fix it quickly!

**Comment by minj** [comment]
Thanks for pointing this out. My players are shitty these days :)
