### ISSUE TITLE
Quote blocks are not created properly when copying in markdown

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1618]
There should be an extra space after a quote block. It's now missing for some reason

**Comment by gleerman** [comment]
This seems to be fixed. To test this, I randomly picked a [forum post](https://www80.hattrick.org/Forum/Read.aspx?t=17294110&n=43&v=4) containing a quote and pasted its markdown in https://stackedit.io/app - which rendered it correcly.

Tested on macOS with Chrome

**Comment by minj** [comment]
You are right, thanks :man_facepalming:
