### ISSUE TITLE
Small css issue in match archive

### ISSUE THREAD

**Issue by murko69** [minj/foxtrick#1619]
A non-issue really, but nevertheless.
The 'ft_season_selectboxID' is a bit misplaced (see image below)
Deactivating my own CSS makes no difference

#ft_season_selectboxID {
	float: right;
	margin-top: 20px;
}
Above margin-top changed to 10px seems to work for the vertical alignement

![c395014d-49f1-463e-9792-4e3ad7145cb7](https://user-images.githubusercontent.com/12071221/53679247-770e5880-3cca-11e9-9211-42c9b514051f.png)

**Comment by minj** [comment]
I should make a rule that any issue mentioning CSS should have pull request attached to it :laughing:

**Comment by murko69** [comment]
Something has changed on this page **yet again** making the original margin-top:20px work as it should again.

**Comment by minj** [comment]
:roll_eyes:
