### ISSUE TITLE
Foxtrick always asks for permission on Chrome

### ISSUE THREAD

**Issue by bimbo1989** [minj/foxtrick#1626]
I'm using the latest Chrome 76.0.3809.100 on Windows 10, and FoxTrick always asks for authorization via chpp in any page (home, players, fixtures). I always authorize but it keeps asking.
The weird thing is that Foxtrick actually works, it just keeps asking for no reason.

**Comment by eurix1** [comment]
Same Problem here with Firefox 68.0.2 ( 64 bit)

**Comment by Marcx87** [comment]
Same Here...
Foxtrick version: 0.17.9.1318 beta-f98aa308a chrome
Chrome Version: Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by minj** [comment]
> **Get the FoxTrick log**
>
> Visit the page you are having trouble and use the bug report link
>
> [(http://i.imgur.com/yEhsWmG.png)](http://i.imgur.com/yEhsWmG.png)
>
> Follow instructions that appear.

**Comment by Cener10** [comment]
just reset your chrome. go to advanced settings - reset and clean up - and restore your settings to the 
original defaults. worked for me. cheers

**Comment by minj** [comment]
should be working for a while now with https://www.foxtrick.org/beta/download
