### ISSUE TITLE
Forum post cancel button

### ISSUE THREAD

**Issue by GM-Fedelopez** [minj/foxtrick#1633]
The "Cancel" button say "Send" nowwhen writing a forum post...

**Comment by GM-Fedelopez** [comment]
![Screenshot_2019-10-31 Reply » Forum » Hattrick](https://user-images.githubusercontent.com/48441695/67975190-695ef900-fbf2-11e9-9052-ad418d628099.png)

**Comment by murko69** [comment]
Go to Foxtrick settings, search for the module "ForumPreview" and disable that!
Hattrick has made their own preview-feature, stolen from Foxtrick, so the feature is still there. This mixup happend when HT introduced their own version

**Comment by minj** [comment]
I do not know how to feel about this native forum preview. Ours is better imho

**Comment by minj** [comment]
should be fixed in next build

**Comment by murko69** [comment]
> 
> 
> I do not know how to feel about this native forum preview. Ours is better imho

I totally agree. If I remember correct FT's version toggled preview on click while HTs version needs to be closed via a close button (or was it really the same?)
Also, HTs version showed quotes inside a preview in a box with just 70% width. Fixable with CSS though.

But AFAIK Foxtricks version is unusable since HT-Bodin hid the Foxtrick preview in the code when he made their version public so there wouldn't be 2 buttons.
So unless you un-hide yours and hide Hattricks version I guess we are stuck with HT's?

**Comment by minj** [comment]
That's exactly what I did 😁

2019-11-01, pn, 23:38 Micke Olsson <notifications@github.com> rašė:

**Comment by GM-Fedelopez** [comment]
Mmm... Just change some things and show the button as foxtrick preview...
So it will be unhided for all.

**Comment by murko69** [comment]
Hattricks preview will be hidden for everyone using Foxtrick. 
Guessing that's default and no extra setting needed, so don't uncheck the box as I suggested in my first answer. :)
The cancel- button with wrong text will be fixed with this aswell.

**Comment by GM-Fedelopez** [comment]
LOL... Fortunatelly I did never followed your suggestion... :)

**Comment by murko69** [comment]
@minj Just confirming the FT-preview works fine, but could you please change order of the buttons back to the way if was?

The order was always "OK - Cancel - Preview". Now it's "OK - Preview - Cancel".
Unless this was an intended move by you for some reason?

**Comment by minj** [comment]
yes and now.

I've rewritten everything to make less complicated. Thing is... cancel button is available hardly anywhere. And I find it useless. Why not just do back navigation?
