### ISSUE TITLE
Add player salary to SkillTable in TM

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1635]
Available with new design

**Comment by gleerman** [comment]
It appears as if this is already implemented?
<img width="780" alt="Screenshot 2019-11-13 at 17 19 18" src="https://user-images.githubusercontent.com/5098787/68782493-d5515080-0639-11ea-94eb-bcc32b63aa15.png">

**Comment by minj** [comment]
You are indeed correct. I've missed it because it was disabled in customization mode on my end. I've forgotten that I implemented the salary detection along with other changes when new design was introduced.
