### ISSUE TITLE
Score colors for division battles are incorrect

### ISSUE THREAD

**Issue by gleerman** [minj/foxtrick#1637]
##  Short description of the problem
Score colors for division battles are incorrect

## What steps will reproduce the problem?
After a round of division battles, open the division battles page.
The scores for each match are red, green or bold black. The draws are correctly black, but the other scores are red or green, mostly incorrect according to the result of the team in your division

## What is the expected behaviour? 
Either do not colour the scores or apply a colour that is in favour of the teams of your division 

## Foxtrick log URL (see above):
https://pastebin.com/RJUrpBrg

## Any other relevant information. Is it a regression, when it worked/broke etc.
Division battles is a brand new HT feature, so no wonder Foxtrick as some unexpected behaviour with it

**Comment by minj** [comment]
I am sorry but I see nothing on that page. Could you provide a screenshot?

**Comment by minj** [comment]
I will not ever solve this issue without your cooperation

**Comment by murko69** [comment]
This was a HT-bug and AFAIK this is fixed by them as well.
The colors on the "live page" for division battles was incorrect.
Wins showed as red and losses as green (when watching via my own league).
I don't see this error anymore

**Comment by gleerman** [comment]
Exactly. Hence I will close this issue.
