### ISSUE TITLE
SeriesTransfers: duplicate entries

### ISSUE THREAD

**Issue by ciskype** [minj/foxtrick#1638]
## Short description of the problem
SeriesTransfers: show duplicate players in the transfer list

## What steps will reproduce the problem?
Go to series page, look in the SeriesTransfers section

## What is the expected behaviour? What is the actual behaviour? Please provide any relevant screenshots.
The Transfer list table must display unique players
<img width="1040" alt="Screen Shot 2019-11-15 at 11 31 05" src="https://user-images.githubusercontent.com/10257215/68975183-3ecc8d00-07fb-11ea-84a2-55078d8cbc03.png">

**Comment by minj** [comment]
What is the version of Foxtrick that you use>

**Comment by ciskype** [comment]
Preferinţe FoxTrick 0.17.0.1 hosted chrome
<img width="682" alt="Screen Shot 2019-11-16 at 07 55 41" src="https://user-images.githubusercontent.com/10257215/68988849-9e03bf00-0846-11ea-9b19-bc59aee0fcf5.png">

**Comment by minj** [comment]
please use https://foxtrick.org/download/beta

**Comment by ciskype** [comment]
yep - it works fine for beta
