### ISSUE TITLE
HTMS Points error in Turkish Language 

### ISSUE THREAD

**Issue by ahmetysfl** [minj/foxtrick#1651]
Hello Everyone,

HTMS points in player page is showing as follows in English Language. 

![English_HTMS](https://user-images.githubusercontent.com/18581276/82213167-63c1ca00-991c-11ea-817b-79ed6b4ba5ab.png)
]

In Turkish language;
![Turkish_HTMS](https://user-images.githubusercontent.com/18581276/82213205-720fe600-991c-11ea-81a0-fb781aeb6d5f.png)

Is it a problem? How to fix?

Thank you,

**Comment by minj** [comment]
See my change at: https://crowdin.com/translate/foxtrick/10781/en-tr#q=HTMSPoints.AbilityAndPotential

If you find more issues with the translation, please sign up at crowdin and correct them yourself. They are integrated automatically every day into foxtrick beta channel
