### ISSUE TITLE
Support for teams from new Countries

### ISSUE THREAD

**Issue by manoloalesys** [minj/foxtrick#1653]
Hello, i am manager from a team in Madagascar and in country Name instead of Madagascar or Madagasikara (english).

Thanks for helping

**Comment by minj** [comment]
This is currently only supported on Firefox: https://www.foxtrick.org/beta/foxtrick-0.17.9.1670.xpi

**Comment by minj** [comment]
blocked on #1657

**Comment by minj** [comment]
solved
