### ISSUE TITLE
New training change entries break XP calculation in performance history

### ISSUE THREAD

**Issue by gkotschy** [minj/foxtrick#1654]
Location: MyClub->Players->PlayerXYZ->PerformanceHistory screen
Issue: New training change entries break XP calculation in performance history
Reproduction: Change training type or intensity, wait until training update, play a match.
Expected behavior: XP calculation should indicate last XP increase in last match in which XP increased and calculate XP gained since that match.
Actual behavior: XP calculation indicates that the first match after the training change is last XP increase and only calculates XP gained since that match.
Foxtrick log URL: https://pastebin.com/77YeLj0R
AOB: Broken since introduction of new training history feature in Hattrick.

![image](https://user-images.githubusercontent.com/66754428/84324823-a4a6aa80-ab79-11ea-8f59-7e1a566785c7.png)

**Comment by minj** [comment]
Thanks. I am aware of the issue and it has been fixed on Firefox but there are no new Chrome builds for a while. I am working on it

**Comment by minj** [comment]
blocked on #1657

**Comment by minj** [comment]
should be working for weeks now
