### ISSUE TITLE
Mercattrick integration

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1656]
GET https://api.mercattrick.com/v1/players/stats/id1,id2,...,id25

Response example:

```json
    [
      {
        "id": 436441778,
        "filters_count": 47,
        "bookmarks_count": 1
      },
      {
        "id": 438100968,
        "filters_count": 26,
        "bookmarks_count": 0
      }
    ]
```

**Comment by minj** [comment]
Icons are needed for SkillTable

![image](https://user-images.githubusercontent.com/1035523/84576727-4c5cec00-adb7-11ea-8a0b-d573b63c80d4.png)

**Comment by dromichet** [comment]
Here is the logo ... in PNG format, as SVG would be bigger in size and there's no need to support scaling.

![Mercattrick Logo-04](https://user-images.githubusercontent.com/5149147/84577516-94830b00-adc5-11ea-8635-c1a76912c637.png)

You mentioned you need two different ones but I don't see exactly where you want to use them. On the headers I see only texts. Do you want to place a small logo next to the value?

**Comment by minj** [comment]
Rather instead of the text

**Comment by dromichet** [comment]
Ok. I'll try to come-up with something

**Comment by dromichet** [comment]
![bookmarks_count](https://user-images.githubusercontent.com/5149147/84598932-f3ed2380-ae76-11ea-8d9e-dbfba4b5eeba.png)
![filters_count](https://user-images.githubusercontent.com/5149147/84598933-f485ba00-ae76-11ea-8cd8-fbf6310cf5a3.png)

Do you think these will do?

**Comment by minj** [comment]
Yep, I think so

**Comment by dromichet** [comment]
Hi. I've implemented the integration and created a pull request.
When you have time, please have a look over the implementation.
