### ISSUE TITLE
Wrong U21 World Cup/Continental Cup Eligibility

### ISSUE THREAD

**Issue by Gundor** [minj/foxtrick#1660]
There has been an update of U21 competitions, with introduction of Continental Cup.

An example : https://i.imgur.com/RT5RQFK.png

**Comment by minj** [comment]
@rferromoreno wanna take it?

**Comment by rferromoreno** [comment]
@minj yes Sir!

I already worked on it. I only have to put it into Foxtrick code. Going to do it ASAP. Just wanting to mantain keep code for old World CUp format as well.

**Comment by minj** [comment]
Don't forget to fetch first. I had merge huge changes recently

**Comment by minj** [comment]
@rferromonero ping?

**Comment by Gundor** [comment]
an update would be really welcome, because the new generation of player is coming and can play the new Regional Cup

**Comment by FloJ12** [comment]
The Text U21 is now okay, but the eligibility round is still not correct. For example: Florian Brandl [(296675160)](https://www87.hattrick.org/Club/Players/YouthPlayer.aspx?YouthPlayerID=296675160) should be eligible until Finals, but Foxtrick says he can play until Semifinals

**Comment by rferromoreno** [comment]
> The Text U21 is now okay, but the eligibility round is still not correct. For example: Florian Brandl [(296675160)](https://www87.hattrick.org/Club/Players/YouthPlayer.aspx?YouthPlayerID=296675160) should be eligible until Finals, but Foxtrick says he can play until Semifinals

Nice catch. I think there are actually 3 defects. One with the player days offset, other one with the CC match #4 (its not taken into account), and the last one between semifinals and finals

I need to check if this match day schedule was always this way

**Comment by rferromoreno** [comment]
> The Text U21 is now okay, but the eligibility round is still not correct. For example: Florian Brandl [(296675160)](https://www87.hattrick.org/Club/Players/YouthPlayer.aspx?YouthPlayerID=296675160) should be eligible until Finals, but Foxtrick says he can play until Semifinals

Ok, adding more info here. I can confirm that initially the calendar was another, so I will need to recreate the offets for the matches.  [This was the initial schedule](https://docs.google.com/spreadsheets/d/1fcfBnqIj_v-gpElhD9pWt5lKhoLC--ZT_Hf37Ytx8sY/edit?usp=sharing), but it seems it changed when they started in order to do the Live Draw.

**Comment by rferromoreno** [comment]
@FloJ12 I already created the [PR here](https://github.com/minj/foxtrick/pull/1686) and tested the case with your player. But if you have more players to test please go ahead, you can clone my branch into your local.
