### ISSUE TITLE
duplicate ft-staff-icons in sneak-peek

### ISSUE THREAD

**Issue by murko69** [minj/foxtrick#1670]
In Hattricks sneak-peek feature for forums, where you can see the forum directly on series pages for example, the ft-staff-icon is duplicated when you click the preview-button (the magnifying glass)
Maybe this is an old issue because I always had the sneak-peek hidden, but today I made som CSS-changes to HTs feature and I noticed this

![Screenshot](https://user-images.githubusercontent.com/12071221/93809393-81e26280-fc4d-11ea-9317-0bd5596e9def.png)

**Comment by minj** [comment]
thanks for the report
