### ISSUE TITLE
Package is invalid: "CRX_HEADER_INVALID"

### ISSUE THREAD

**Issue by guestr174** [minj/foxtrick#1681]
When I try to install foxtrick version 0.17.9.2157 on Chrome I get the message Package is invalid: "CRX_HEADER_INVALID".

**Comment by murko69** [comment]
You could try right click on the file and "save as..." and then drag-drop to browser maybe

**Comment by guestr174** [comment]
I get the same error message...

**Comment by murko69** [comment]
This 'workaround' seems to work for a lot of people: 

Right click and save the .crx file anywhere.
Change file type .crx to .zip and then extract zip file to a folder.
Open the extensions page in Chrome or navigate to “chrome://extensions” from the address bar.
Check the “Developer mode” to enable the developer mode.
Click “Load unpacked” and select folder of extracted zip file

**Comment by guestr174** [comment]
Ok. It installed now and seems to be working. However, there are errors reported in the extensions page:

 



 

Thank you

**Comment by minj** [comment]
Please use this link on chromium browsers: https://chrome.google.com/webstore/detail/foxtrick/bcbhbklnhonhojfmkobhhjkfaggkoali
