### ISSUE TITLE
Rating Box not appearing again due to the implementation of copy options

### ISSUE THREAD

**Issue by Renzoco07** [minj/foxtrick#1687]
I have this skin on Skin Plugin:

#ft_simulation_ratings-new{position:relative;transform:none;max-width:610px}

What changes do you have to do :)

Thank you

**Comment by Ben-Zahler** [comment]
@Renzoco07 I raised a PR that fixes this for me: https://github.com/minj/foxtrick/pull/1688

**Comment by Renzoco07** [comment]
> @Renzoco07 I raised a PR that fixes this for me: #1688

Hello Ben! 
Excuse me, I am an ignorant person in coding hehe, what do we have to do?
Copy all the codes on the Skin Pluggin section?
Thank you

**Comment by Ben-Zahler** [comment]
@Renzoco07 no, chanign the skin is not enough. for "normal" humans, this needs to get reviewed and merged by @minj

**Comment by Renzoco07** [comment]
> @Renzoco07 no, chanign the skin is not enough. for "normal" humans, this needs to get reviewed and merged by @minj

Ok I understand :)
Lets wait for the experts.
Best regards from Perú!

**Comment by minj** [comment]
Let me know if this is fixed in next build (in circa 2 hours, depending on browser)

**Comment by minj** [comment]
no feedback? does that mean issue is resolved?

**Comment by Ben-Zahler** [comment]
@minj for me it's working with latest build. I think Firefox should automatically load the latest version, right?
@Renzoco07 can you verify if this is fixed?
