### ISSUE TITLE
Missing experience in player performance history page

### ISSUE THREAD

**Issue by ancath71** [minj/foxtrick#1691]
Hello, I see foxtrick is no longer displaying the summary with the player current estimated experience .

Matches since last skill-up | Matches | Minutes | Min. XP Pts. | Max. XP Pts.
-- | -- | -- | -- | --
Sum |   | 0 | 0
Experience |   | 0 | 0
I assume this is due to the changes in the experience given by national team games. Will this be fixed? Any ETA?
Thank you very much for your work in making a better HT experience for all of us!

**Comment by minj** [comment]
Hello, please provide a link to the player in question

**Comment by 19711938** [comment]
Anch'io ho lo stesso problema a tutti giocatori non mi calcola più l'esperienza dandomi sempre che ha 0 di esperienza

**Comment by ancath71** [comment]
> Hello, please provide a link to the player in question

Hello this is the player: 456904429
Andrew Sullivan [playerid=456904429]
21 anni e 78 giorni, Prossimo compleanno: 20-06-2022

Nazionalità: Barbados

Una persona gradevole, equilibrata e disonesta. 
È accettabile (6)(6) in esperienza e debole (4)(4) in carisma. Il suo livello di fedeltà è divino (20)(20).
Fa parte della squadra nazionale U21 Barbados!

Proprietario [b]TWR-Helmets[/b] (dal 19-12-2020 (13/76), 4s 9set 3gg)

TSI 77 180
Stipendio 5 208 £(4 340 £) /settimana +20% essendo un giocatore internazionale
 83 328 £/stagione
Specialità [b]-[/b]
Forma buono 7
Resistenza eccellente 8
HTMS Punti: [b]Abilità:1221 / Potenziale:2125[/b]
Miglior posizione: Terzino difensivo (12.78)

[table]
[tr][th]Parate[/th][td]disastroso (1)[/td][th]Difesa[/th][td][b]fuoriclasse (13)[/b][/td][/tr]
[tr][th]Regia[/th][td][b]accettabile (6)[/b][/td][th]Cross[/th][td][b]straordinario (10)[/b][/td][/tr]
[tr][th]Passaggi[/th][td][b]formidabile (9)[/b][/td][th]Attacco[/th][td]scarso (3)[/td][/tr]
[tr][th]Calci piazzati[/th][td][b]magnifico (12)[/b][/td][/tr]
[/table]
![Sullivan](https://user-images.githubusercontent.com/42704741/168924607-4ae8e6f1-aa46-48d5-805c-d23e09248015.PNG)

**Comment by minj** [comment]
I have made some fixes in 0.17.9.2462. Let me know if you find players still broken
