### ISSUE TITLE
Live games header position issue

### ISSUE THREAD

**Issue by megatronium83** [minj/foxtrick#1735]
## Short description of the problem
when I have a live match, the link in the header is cover by the menu bar
## What steps will reproduce the problem?
login when you have a match 
## Any other relevant information. Is it a regression, when it worked/broke etc.
![image](https://github.com/minj/foxtrick/assets/78934743/b5ec48dd-5cf1-4b32-9884-2440ab2e414f)

**Comment by sbshow** [comment]
Already reported on [https://github.com/minj/foxtrick/issues/1734](url)

**Comment by megatronium83** [comment]
duplicate of 
https://github.com/minj/foxtrick/issues/1734
