### ISSUE TITLE
Eligibility for U20 World Cup

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#893]
Original [issue 893](https://code.google.com/p/foxtrick/issues/detail?id=893) created by [paul.barthelemy84](mailto:paul.barthelemy84@gmail.com) on 2012-01-28T11:46:10.000Z:

It would be great to have a small table on the right (player page) that shows the ongoing and upcoming U20 Worldcups and shows the eligibility in weeks for this specific player.

EG:

WC XIX - Season 29 - Q1
14/14

WC XX - Season 30 - Q2
7/14

...

**Comment by rferromoreno** [comment]
I started working on this.

Ok, not exactly this, but something similar.

I'll bring news on next days.

**Comment by rferromoreno** [comment]
@minj Sorry, what do you mean? The NT Players List?

If there is any bug reported on the module please let me know and I will try to fix it ASAP.

**Comment by minj** [comment]
yes, NT players

Although `allPlayers' definition includes many esoteric HT pages as well. All of them should be tested and fixed where appropriate or disabled otherwise

**Comment by minj** [comment]
@rferromoreno this is what I had in mind: c2427d6
